OBJS-$(CONFIG_HSV) += hsv/rb/rb.o
OBJS-$(CONFIG_HSV) += hsv/utils/utils.o
OBJS-$(CONFIG_HSV) += hsv/dft/dft.o
OBJS-$(CONFIG_HSV) += hsv/estimator/estimator.o
OBJS-$(CONFIG_HSV) += hsv/suppressor/suppressor.o	
OBJS-$(CONFIG_HSV) += hsv/hsv.o

OBJS-$(CONFIG_HSV) += $(HSV-OBJS-yes)
